name:                grade-sender
version:             0.1.0.0
github:              "cvlad/grade-sender"
license:             BSD3
author:              "Vladimir Ciobanu"
maintainer:          "git@cvlad.info"
copyright:           "2018 Vladimir Ciobanu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Grade email sender
# category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cvlad/grade-sender#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall -O2 -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
  dependencies:
  - attoparsec
  - bytestring
  - cassava
  - HaskellNet
  - HaskellNet-SSL
  - mtl
  - text
  - unordered-containers
  - vector
  default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns

executables:
  grade-sender-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grade-sender

tests:
  grade-sender-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grade-sender
